
services:
  backend:
    image: ghcr.io/zixhd/recipe-api:latest
    container_name: recipe-api
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      APP_VERSION: ${APP_VERSION}
    ports:
      - "8080:8080"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

